[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/webhook/facebook"
  to = "/.netlify/functions/facebook-webhook"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
